### ISSUE TITLE
Rotating shape analyzers doesn't rotate the art

### ISSUE THREAD

**Issue by Hyperion-21** [tobspr/shapez.io#944] opened 2020-10-28 01:31 UTC
https://www.reddit.com/r/shapezio/comments/jj3wp7/shape_analyzer_visualization/

**Comment by santa-klaus** [comment] 2020-10-29 09:26
Duplicate of https://github.com/tobspr/shapez.io/issues/893

**Closed** 2020-12-09 12:43 UTC
