### ISSUE TITLE
Inconsistency in Shape Merging

### ISSUE THREAD

**Issue by macdjord** [tobspr/shapez.io#344] opened 2020-06-30 00:35 UTC
For the final shape, I create it by merging [Ru----Cw](https://viewer.shapez.io?Ru----Cw) with [--Cw----:----Ru--](https://viewer.shapez.io?--Cw----:----Ru--). Since these shapes have no quadrants in common, it should not matter in which order they are merged, but this is not the case: if [--Cw----:----Ru--](https://viewer.shapez.io?--Cw----:----Ru--) is the left input, the shapes merge as expected to form [RuCw--Cw:----Ru--](https://viewer.shapez.io?RuCw--Cw:----Ru--), but if [Ru----Cw](https://viewer.shapez.io?Ru----Cw) is the left input, the result is inexplicable flattened, resulting in [RuCwRuCw](https://viewer.shapez.io?RuCwRuCw):
![Merge_error](https://user-images.githubusercontent.com/4250155/86069434-d1970080-ba47-11ea-834d-ef9f18bf07a0.png)

**Comment by ChucklesTheBeard** [comment] 2020-06-30 01:01
duplicate of #157

**Comment by macdjord** [comment] 2020-06-30 03:06
@ChucklesTheBeard That issue was closed a week ago; this bug is current as of 6 hours ago.

**Comment by ChucklesTheBeard** [comment] 2020-06-30 11:21
It was closed as "technically not a bug", which remains relevant.

Also a duplicate of #277

**Comment by TheTrueSCU** [comment] 2020-07-05 18:12
This is also a duplicate of my issue #313 which implies that many people seem to feel that the merge logic needs to be looked at again as it is causing lots of confusion.

One of the sub-products for producing the final shape is ------Cw:----Ru-- which would be impossible to make if there was a realworld analog

**Comment by jjshoe** [comment] 2020-07-10 15:57
I would have to agree that this just seems to function in no logical way when playing the game. The sheer number of open/duplicate issues indicates something needs to change.

**Comment by tobspr** [comment] 2020-07-18 13:06
https://trello.com/c/IcL69eaa/272-level-18-stacker-bug

**Closed by tobspr** 2020-07-18 13:06 UTC
