### ISSUE TITLE
[Bug? Intended?] Belt reader speed is lower than belt speed

### ISSUE THREAD

**Issue by Gemberkoekje** [tobspr/shapez.io#877] opened 2020-10-14 15:52 UTC
I have a belt speed of 14, which I know because my chain extractors helpfully tell me this.
However, when I add a belt reader, it starts out at 14 and then slowly decreases to 12. This is at 7x belt speed upgrades.

I don't think a belt reader is an extraction tool, nor a mixing/painting tool. So this is weird.

And I actually did a test to confirm it with a storage, and the storage without the belt reader fills up faster than the storage with the belt reader.

I really like the belt readers, as it allows me to check whether I'm doing things optimally, but I will completely stop using them if they actually screw up my optimal-ness by being slower than the actual belts.

**Comment by EmeraldBlock** [comment] 2020-10-14 16:17
Duplicate of #781 (Yes, that name needs to be changed)

**Comment by Vaelatern** [comment] 2020-10-15 07:29
I observed this behavior... it seems very unusual to me, and does not appear to be belt readers, but does seem related (stuttering despite saturated inputs)

https://files.catbox.moe/i48soc.png

**Comment by API-Beast** [comment] 2020-10-22 19:38
It doesn't seem to happen if the belt reader goes directly into a storage or trash.

**Comment by tobspr** [comment] 2020-12-09 13:00
Fixed in 1.2.2

**Closed** 2020-12-09 13:00 UTC
