### ISSUE TITLE
Feature Request: Zoom to mouse position

### ISSUE THREAD

**Issue by bierale** [tobspr/shapez.io#574] opened 2020-08-17 18:10 UTC
At the moment zooming works around the center of the screen. When you zoom in or out, the origin of the zoom is at the center of the screen.

In many CAD programs you can zoom to the mouse position, which means when you zoom out, the center of the zoom stays at the mouse cursor, same if you zoom in. This has the big advantage of fast movement, you zoom out at position x, you get an "overview", then you move the mouse cursor to the point that you want to see and zoom in at that position.

To further clarify: Try it in Blender. Open Options, under "Navigation" check "Zoom to Mouse Position" and try it out for yourself.

Suggestion: Switch in the options.
Further Suggestion: Switch for reversion zoom direction

**Comment by dengr1065** [comment] 2020-08-17 18:22
already implemented, also duplicate of #346 and #508.

**Comment by bierale** [comment] 2020-08-17 18:27
sorry, I am now tho this and did not see that.

**Closed** 2020-08-17 18:26 UTC
