### ISSUE TITLE
[Bug] Virtual Rotators not outputting anything, other general wire bugs

### ISSUE THREAD

**Issue by TheGoldenProof** [tobspr/shapez.io#902] opened 2020-10-17 17:58 UTC
Unfortunately I haven't been able to reproduce this yet. I had a bunch of things hooked up to one signal, and I either added or removed something and suddenly some of wire devices stopped outputting signals, but other devices were still picking up the signal that they should have been sending, and some were saying they were sending a signal but no signal was coming out. I removed a few things from the line and it fixed itself, but when I put them back everything was working just fine. I don't know what happened or how. If I can get it to happen again I'll attach a picture.

EDIT: I still haven't reproduced it but I think it happened when I was copy and pasting something that caused some wires to connect that shouldn't have. I think it was two outputs, which normally turns red, but for some reason the line wasn't red, and that's when I noticed that things were bugging out.

**Comment by tobspr** [comment] 2020-12-09 12:55
okay, closing since I have no idea how to reproduce this

**Closed by tobspr** 2020-12-09 12:55 UTC
