### ISSUE TITLE
[Bug] Belt Reader lowering belt throughput (14 to 12)

### ISSUE THREAD

**Issue by Some-Yes-Man** [tobspr/shapez.io#912] opened 2020-10-19 15:42 UTC
Currently at Lvl 20 and trying to get the next updates. Belts are up to 14/s.
But when I built belt readers, they slow down my throughput by introducing spaces between items.

![shapezBug](https://user-images.githubusercontent.com/56762082/96473912-80975c00-1232-11eb-9650-7adbf8d2fc56.png)

**Comment by EmeraldBlock** [comment] 2020-10-19 15:59
Duplicate of #781 (misleading name, i know)

**Closed** 2020-12-09 12:53 UTC
