### ISSUE TITLE
[Bug] Belt speed behaviour inconsistent

### ISSUE THREAD

**Issue by redstonedude0** [tobspr/shapez.io#843] opened 2020-10-11 12:21 UTC
Belt(or perhaps extractor) speed appears to get "poisoned" under specific circumstances and becomes slower than it should be.

Steps to recreate are below, ignore the button in the screenshots, there's nothing on the wires layer.

Step 1: Create the following setup: (extractors through readers into a bin)
Upgrades are all at tier VII (x8). Tick rate is 60Hz.
![Screenshot from 2020-10-11 12-50-13](https://user-images.githubusercontent.com/9257710/95677842-56092b80-0bc0-11eb-84fb-998777fcf02d.png)
All readers will say "16"

Step 2: Remove the bottom bin and redirect the items to a long conveyor belt leading to a different bin. The bottom readers will settle on reading 15
![Screenshot from 2020-10-11 12-43-55](https://user-images.githubusercontent.com/9257710/95677831-2f4af500-0bc0-11eb-858c-44593cc433ec.png)

Step 3: Put the original bin back, the readers will continue to read 15. Note that the actual belt speed is 15 - if you scroll the screen to the right the top belt is visible moving faster
![Screenshot from 2020-10-11 12-44-12](https://user-images.githubusercontent.com/9257710/95677829-2bb76e00-0bc0-11eb-8f0b-f4469f8c9841.png)
Note: I left it in this configuration for around 10 minutes and the values of 16/16/15/15 were stable.

I attempted to debug exactly what was going on here - but I got a lot of really random results. I know that at 60Hz precision wil be lost, but surely the belt should still run at roughly the same speed, and only the configuration should matter (not the path to get there - i.e. if the belts were always x15 I could see how that would work, but the 2 belts in the same final configuration actually run at different speeds) - also a 6% decrease in output seems far too high (especially considering the next upgrade is x8->x8.10 , a 1% increase in production (which, due to the precision issues, could theoretically make my throughput worse if it happens to calculate it wrong).

**Comment by anthonyryan1** [comment] 2020-10-12 00:54
Also experiencing this with everyone at Tier 7.

Belts keep reducing down to 12/s (Tier) instead of 14/s (Tier 7).

Based on your report, I'm thinking it's using the Tier minus 1 speed somehow.

**Comment by EmeraldBlock** [comment] 2020-10-12 01:00
This is probably a duplicate of #781.

Try splitting the belt before reading, what happens then?

**Comment by redstonedude0** [comment] 2020-10-12 09:10
I've done some further testing;
I've developed a new, quicker way of reproducing the bug and showing the specific weird behaviour, create the following setup:
![Screenshot from 2020-10-12 09-53-40](https://user-images.githubusercontent.com/9257710/95727096-a7252800-0c71-11eb-880a-302972af8951.png)
Press the button, it will run at 15/s:
![Screenshot from 2020-10-12 09-53-52](https://user-images.githubusercontent.com/9257710/95727141-b5734400-0c71-11eb-91d7-ec3b21d600d5.png)
Then cause a "block update" - place any object directly or diagonally next to the belt and it will start going at 16/s:
![Screenshot from 2020-10-12 09-54-03](https://user-images.githubusercontent.com/9257710/95727234-cf148b80-0c71-11eb-85a4-d8df761884cb.png)
**I have tried on 60, 120, and 180 Hz and all give the same results with this technique** (240Hz seems to work fine though)

Possible related observation:
The throughput of machines is higher than belt speed.
Build this:
![Screenshot from 2020-10-12 10-08-33](https://user-images.githubusercontent.com/9257710/95728103-ffa8f500-0c72-11eb-8b0f-22e960908978.png)
If you connect the priority output using a belt, the capacity of the 1st storage will stay the same as the 2nd fills (+/-1 as it fluctuates), if you connect it using some component (here I used a splitter, a filter also works, etc) then the 1st storage slowly drains
![Screenshot from 2020-10-12 10-08-47](https://user-images.githubusercontent.com/9257710/95728173-19e2d300-0c73-11eb-95d6-3e102bdeab00.png)

**Comment by redstonedude0** [comment] 2020-10-12 09:25
> This is probably a duplicate of #781.
> 
> Try splitting the belt before reading, what happens then?

**Comment by Lilalas** [comment] 2020-10-13 16:19
I am experiencing the same issue on Standalone version 1.2.0.

My belts are on tier 4 (8 items/s), but they carry only 7.5 items/s.

![shapez_belt_speed](https://user-images.githubusercontent.com/10713547/95887295-32d0ae80-0d6f-11eb-8833-f6fa68f19bd7.png)

- Restarting/reloading the game brings the speed back up to 8 items/s.
- Temporarily stopping the belt (by deleting and replacing the trash bin) brings the speed down to 7.5 items/s.

This behavior is reproducible on my system.

**Comment by Lilalas** [comment] 2020-10-13 19:45
This is interesting. It seems that this bug only affects certain levels. Is there something special about these numbers?

**Comment by giodamelio** [comment] 2020-10-29 17:15
I just ran into this same issue. My 8/s belts running at 7.5/s. Also can reproduce reloading fixes it temporarily .

**Comment by tobspr** [comment] 2020-12-09 13:05
Fixed with 1.2.2 (hopefully)

**Closed by tobspr** 2020-12-09 13:05 UTC
