### ISSUE TITLE
belt variants for 2 or 4 belts side-by-side?

### ISSUE THREAD

**Issue by elidoran** [tobspr/shapez.io#1144] opened 2021-04-18 01:59 UTC
We can copy+paste large groups of belts, sure, but, that doesn't make it as easy to create corners as placing a single belt with the belt planner.

If there were variants for 2 belts and 4 belts next to each other, the belt planner could place them the same as a single belt and make the corners for us.

Unlocked at higher levels it would help with placing belt highways.

**Comment by EmeraldBlock** [comment] 2021-04-18 03:04
Duplicate of #890

**Comment by tobspr** [comment] 2022-01-20 18:46
not planned

**Closed by tobspr** 2022-01-20 18:46 UTC
