### ISSUE TITLE
[Visual Bug] Rotating the Trash Can

### ISSUE THREAD

**Issue by tdnzr** [tobspr/shapez.io#1173] opened 2021-05-25 10:07 UTC
Among all machines in the physical or wires layer, only the trash can cannot be rotated manually (e.g. with the R key).

However, if you copy and then rotate _a blueprint_ of a trash can, this does rotate the trash can.

**Comment by tdnzr** [comment] 2021-05-25 10:11
![20210519110223_1](https://user-images.githubusercontent.com/35105157/119480770-4820a900-bd52-11eb-9eeb-cd7c765b0edd.jpg)

**Comment by EmeraldBlock** [comment] 2021-05-25 17:23
This has been considered intentional (an "easter egg").

Duplicate of #1020

**Closed** 2021-05-25 17:23 UTC
