### ISSUE TITLE
[1.4.4] Belt limit?

### ISSUE THREAD

**Issue by GigaBajcior** [tobspr/shapez.io#1298] opened 2021-09-10 14:56 UTC
Hello,

I have all updates on Level 50 but it looks that belst are somehow limited to 19.9 PCs/s.
Is it bug or do I something wrong?
Regards
Artur

![image](https://user-images.githubusercontent.com/1894864/132873341-7756e8c5-25f8-4e9e-9781-34e49f0c5b18.png)
![image](https://user-images.githubusercontent.com/1894864/132873400-047ee4de-cc8e-439b-a6af-de1bd9e9ed91.png)
![image](https://user-images.githubusercontent.com/1894864/132873527-5df919ce-6b92-447b-8eab-3a8291361b9b.png)

**Comment by GigaBajcior** [comment] 2021-09-21 20:11
Hi.
I found that belt limit depends on FPS set in options:

On 60FPS I have 20 pcs/s
![image](https://user-images.githubusercontent.com/1894864/134240260-f908c0de-7444-4648-8c53-2c733a5ed7d8.png)

On 30FPS I have 14,9 pcs/s
![image](https://user-images.githubusercontent.com/1894864/134240412-7fff8ea5-f0c0-40a5-af1a-7addbd3790a4.png)

On 120 FPS 23,4 and on 180 FPS finally 23,6 as it should be.

Regards
Artur

**Comment by EmeraldBlock** [comment] 2021-09-21 20:23
duplicate of #781

**Closed** 2022-01-20 21:12 UTC
