### ISSUE TITLE
Is there way to unlock all buildings and logic modules on first level?

### ISSUE THREAD

**Issue by cawa-93** [tobspr/shapez.io#1478] opened 2022-09-19 14:11 UTC
Yesterday I finished the game somewhere around level 176. I really enjoyed building the MAM (Make averething machine) and would like to play with it some more. I would be interested in building an MAM that would go through all the levels of the main game on its own. But for this you need to have all the building and logic modules in the first levels. Something like New Game+. Is there any way to do this? That would be really fun.

**Comment by EmeraldBlock** [comment] 2022-09-19 18:58
duplicate of #538

**Closed** 2022-09-20 06:17 UTC
