### ISSUE TITLE
Game does not show stopped in Steam Client

### ISSUE THREAD

**Issue by RangerDanger84** [tobspr/shapez.io#929] opened 2020-10-24 15:13 UTC
Not sure if this is a Steam issue, or possibly a missed flag trigger the game is supposed to set in Steam, but beginning yesterday (10/23/20), when I exit the game, it is still shown as running in Steam.  This causes a need to restart Steam in order to open shapez.io again for a new session.

**Comment by EmeraldBlock** [comment] 2020-10-24 16:05
Duplicate of #848

**Closed** 2020-12-09 12:50 UTC
