### ISSUE TITLE
Right clicking to deselect switch deletes switch.

### ISSUE THREAD

**Issue by FeedTheChunk** [tobspr/shapez.io#1018] opened 2020-12-08 01:07 UTC
[Steam Stand-a-lone] When you place a switch and then right click to deselect it, it deletes the switch.  All other items you can deselect with a right click and not delete the item.  Not what I would consider a bug but an inconsistency with how other items get deselected.

**Comment by EmeraldBlock** [comment] 2020-12-08 01:14
Duplicate of #831

**Closed** 2020-12-08 01:25 UTC
