### ISSUE TITLE
Can't combine text with shape icons

### ISSUE THREAD

**Issue by tutacat** [tobspr/shapez.io#1611] opened 2024-12-29 19:13 UTC
When setting names for waypoints, you can only show a shape icon if that is the only text (say "CuCuCuCu". If you want the waypoint called "⊕ Mine", it just shows up as "CuCuCuCu Mine"

**Comment by EmeraldBlock** [comment] 2024-12-29 23:48
Duplicate of #559

**Closed as not planned by EmeraldBlock** 2024-12-29 23:48 UTC
Labels: duplicate
