### ISSUE TITLE
[BUG] Belts slowing down after backing up.

### ISSUE THREAD

**Issue by defry1234** [tobspr/shapez.io#1015] opened 2020-12-06 22:42 UTC
Upgrades I used were 9.0, 8.9 8.7, 8.7 respectively.
I used 5 extractors on one belt split to 4 cutters to test this on a clean map.
Initially the setup runs fine, slowly backing up the input belt as expected due to the cutters using less than provided.
When the belt backs up all the way however, it slows down causing the belt to no longer be backed up.
This new, slower input rate is maintained until the belt is cut, drained and reconnected, in which the above reoccurs.
Placing items next to the input belt or extractors seems to also reset the speed to normal.
The slower input rate is measured at 15  on 60Hz and 17.1 on 120Hz and 240Hz.
Strangely 30Hz immediately slows down to 15 while never backing up the belt.

**Comment by EmeraldBlock** [comment] 2020-12-06 22:56
Duplicate of #781 (misleading title, read the last message), fixed by #999

**Closed** 2020-12-09 12:23 UTC
