### ISSUE TITLE
Visual glitch when resource patches are too small

### ISSUE THREAD

**Issue by MathiasSven** [tobspr/shapez.io#516] opened 2020-07-29 20:54 UTC
As shown below, the resource patch is only 1 block wide so on the map view it gets partially cut off.
![image](https://user-images.githubusercontent.com/24759037/88852063-1ab3af00-d1c4-11ea-89d7-1e2d883b2bad.png)

**Comment by bjornstar** [comment] 2020-08-01 14:30
I'm not able to reproduce this, even if I generate tiny patches that are just two blocks tall and 1 block wide nothing is cut off.

Here's what I see when I make the patches smaller:
![shapez-one-wide-patch](https://user-images.githubusercontent.com/20630/89103607-e7845080-d44d-11ea-9d27-2b7d0135a5d2.png)

Do you have a save file you can share?

**Comment by dengr1065** [comment] 2020-08-01 14:36
That happens on chunk borders, is also a known bug, but that is really low priority.

**Comment by tobspr** [comment] 2020-09-14 13:22
Should be fixed with the wires update, if not please reopen then :)

**Closed by tobspr** 2020-09-14 13:22 UTC
