### ISSUE TITLE
[Feature Request] Flipped cutters, mixers, stackers, double painters.

### ISSUE THREAD

**Issue by Mattisonfire511** [tobspr/shapez.io#986] opened 2020-11-12 22:58 UTC
i think you should add more flipped versions of buildings, i think flipped cutters and stackers would be REALLY useful for compacting designs.

**Comment by EmeraldBlock** [comment] 2020-11-12 23:03
Duplicate of #643 and already in the trello board (https://trello.com/c/QlYfbg9c/270-allow-mirroring-blueprints-all-buildings)

(They refer to all buildings, but I think it's close enough to constitute a duplicate)

**Comment by tobspr** [comment] 2020-12-09 12:32
Not planned

**Closed by tobspr** 2020-12-09 12:32 UTC

**Comment by m0rtalis** [comment] 2021-12-26 14:02
Can we at least get the mirrored version of the filter as mentioned in #631 
I get the reasoning why no mirrored versions for all buildings are implemented, but without a mirrored version of the filter it's impossible to build even semi-symmetrical machines. I would put the filter in the same category as the balancer, merger, splitter or painter which all have mirrored versions or a symmetrical by themselves.
For now it is just really annoying to work with the filter.

Thank you

**Comment by EmeraldBlock** [comment] 2021-12-26 17:42
could've written a comment there and not here lol

**Comment by m0rtalis** [comment] 2021-12-29 19:15
Yep true. Sorry worked just too long on my MAM and was frustrated at the time .
Still I think my points are valid :wink:
