### ISSUE TITLE
[BUG] Painter (Double) working slower as expected

### ISSUE THREAD

**Issue by bieniajl** [tobspr/shapez.io#1124] opened 2021-03-24 00:44 UTC
![20210324011721_1](https://user-images.githubusercontent.com/38155573/112236679-50b90e00-8c41-11eb-8ffb-c21ba3109859.jpg)

As can be seen in the provided screenshot, the double painter recieves around 1.9 items/s and outputs around 3.9 items/s.
What I would expect would be an intake of 2.14 on each lane, with an output of 4.28.

Running on Windows10 (Version 1909)
Currently on version: 1.3.0@ Production@27d94bd2 (Latest Steam update)

**Comment by EmeraldBlock** [comment] 2021-03-24 00:59
Duplicate of #842

**Comment by striker9921** [comment] 2021-04-03 18:42
In #842, it is mentioned that #1023 may fix this bug. However, #1023 has a label "looks-good-needs-testing", and this issue still persists as of v1.3.0 on steam. As shown in the image below, the expected input of each shape channel and the color channel should be 1.75, but it appears to be just over 1.5, and the output is around 3.2 rather than 3.5

![double-painter-slower-than-expected](https://user-images.githubusercontent.com/44536394/113488061-5e606600-9481-11eb-8b71-4f382c8eb5c3.JPG)

Since #1023 is fixed, I think this should need more attention than being marked a duplicate of #842.

**Comment by EmeraldBlock** [comment] 2021-04-03 19:05
> In #842, it is mentioned that #1023 may fix this bug.
That is because #1023 marks itself as fixing #842. Unfortunately, it does not mark itself as fixing #1124 because time travel has not been invented yet.

#1023 is still open (not accepted or rejected) anyway, so it doesn't affect anything.

And anyway, none of this changes that this issue is reporting the exact same bug as #842.

**Comment by striker9921** [comment] 2021-04-03 21:13
Ok, I misunderstood the wording in #1023, I thought the issue in #1023 is fixed already, but this bug still persists. So, I was trying to call attention to this bug.

**Comment by EmeraldBlock** [comment] 2021-04-03 21:24
Although this bug is pretty annoying, not providing any new information ("that it still exists" is assumed from the issue being open) is not very helpful. Just upvote the issue comment or the trello item (trello board linked in README)

**Comment by tobspr** [comment] 2022-01-20 21:14
Will be fixed with 1.5.0

**Closed by tobspr** 2022-01-20 21:14 UTC
