### ISSUE TITLE
[Bug] Some selections paste incorrectly

### ISSUE THREAD

**Issue by Telos06** [tobspr/shapez.io#946] opened 2020-10-28 06:35 UTC
Observed behavior: Copying a particular configuration and then pasting creates an inexact copy.

Expected behavior: Pasted configuration should exactly match the copied version. This bug requires the user to manually edit the configuration after each paste operation.

Here's an example from real play. Original is on the left, the bad copy is on the right:
![image](https://user-images.githubusercontent.com/16791429/97400818-fcd21500-18ac-11eb-8844-9c3cd09ff184.png)

Here is a simplified version
![image](https://user-images.githubusercontent.com/16791429/97400854-0b203100-18ad-11eb-9f41-b4c0b7a275a4.png)

**Comment by EmeraldBlock** [comment] 2020-10-28 15:42
Duplicate of #214

**Comment by mikewallstedt** [comment] 2020-10-30 04:25
I left a comment over on #214, but I see that issue was marked as closed. Would it better to continue the investigation here, or to reopen #214?

**Comment by tobspr** [comment] 2020-12-09 12:42
Tracking here: https://trello.com/c/rHYkhx4Z/294-pasting-blueprints-sometimes-breaks-buildings-pastes-incorrectly

**Closed by tobspr** 2020-12-09 12:42 UTC
