### ISSUE TITLE
Belts sometimes go slow for no apparent reason

### ISSUE THREAD

**Issue by harrison-munitz** [tobspr/shapez.io#954] opened 2020-10-31 08:21 UTC
Some real funny business going on. My belts are supposed to do 14/s. For some reason, certain belt layouts run at less. Usually 12/s and sometimes 13.5 (both while at full throughput). The only way to show it is to just put a picture.
This particular configurating I've found consistently produces all 3 speeds. All of the extractor rows are 14/s. It works with all materials, in any direction, and anywhere on the map.
![shapez io Standalone 10_31_2020 4_20_15 AM](https://user-images.githubusercontent.com/39506923/97774697-6746b780-1b30-11eb-880a-f465c9faef27.png)

**Comment by EmeraldBlock** [comment] 2020-10-31 16:29
This is a fault of the **reader**.

Duplicate of #781

**Comment by tobspr** [comment] 2020-12-09 12:40
Fixed in 1.2.2 (hope
fully)

**Closed** 2020-12-09 12:40 UTC
