### ISSUE TITLE
Vertical and horizontal flip for the cutter, stacker, painter and color mixer

### ISSUE THREAD

**Issue by Azertooth** [tobspr/shapez.io#1293] opened 2021-08-29 18:31 UTC
imho is a really needed feature, it's on the roadmap or there's some mod that implement it?

**Comment by zwollner** [comment] 2021-08-29 18:36
tobspr has said that it's not going to happen, and there are already mods for it.

**Comment by EmeraldBlock** [comment] 2021-08-29 19:13
duplicate of #986

**Comment by Azertooth** [comment] 2021-08-29 19:27
> 
> 
> tobspr has said that it's not going to happen, and there are already mods for it.

can you please link me the mod?

**Comment by darkwater4213** [comment] 2021-10-29 18:14
> https://discord.gg/rWuYY839bF is one (seems there's no one official link)

Oh, thanks. Now I don't have to find one myself :)

**Closed** 2022-01-20 18:42 UTC
