### ISSUE TITLE
[Feature Request] MacOS version in steam

### ISSUE THREAD

**Issue by LauLaman** [tobspr/shapez.io#1100] opened 2021-03-13 21:44 UTC
Would be great to install this game on my mac trough stream.

Since we're talking about an electron app this seems likely to be easy.

**Comment by DJ1TJOO** [comment] 2021-03-13 21:51
I think tobspr had problems building for mac

**Comment by EmeraldBlock** [comment] 2021-03-13 22:02
Duplicate of #684

**Closed** 2022-01-20 21:14 UTC
